SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=220 # Tuned Yellow
SPACESHIP_DIR_COLOR=084 # Light green
SPACESHIP_CHAR_COLOR_SUCCESS=046 # Bright green
SPACESHIP_GIT_BRANCH_COLOR=206 # Pink
SPACESHIP_GIT_STATUS_COLOR=226 # Yellow
SPACESHIP_PACKAGE_COLOR=105 # Light indigo
SPACESHIP_PACKAGE_SYMBOL=""
SPACESHIP_NODE_COLOR=059 # Dark green

SPACESHIP_EXEC_TIME_SHOW=true

SPACESHIP_GIT_STATUS_UNTRACKED=" untracked "
SPACESHIP_GIT_STATUS_ADDED=" added "
SPACESHIP_GIT_STATUS_MODIFIED=" modified "
SPACESHIP_GIT_STATUS_RENAMED=" renamed "
SPACESHIP_GIT_STATUS_DELETED=" deleted "
SPACESHIP_GIT_STATUS_STASHED=" stashed "
SPACESHIP_GIT_STATUS_UNMERGED=" unmerged "
SPACESHIP_GIT_STATUS_AHEAD=" ahead "
SPACESHIP_GIT_STATUS_BEHIND=" behind "
SPACESHIP_GIT_STATUS_DIVERGED=" diverged "